language: node_js
env:
- NODE_ENV=development
before_install:
- npm i -g npm
install:
- npm install
jobs:
  include:
  - name: Build Node 8
    script: npm run build
    node_js: 8
  - name: Build Node 9
    script: npm run build
    node_js: 9
  - name: Build Node 10
    script: npm run build
    node_js: 10
  - name: Linter
    script: npm run lint
    node_js: 10
  - name: Tests
    script: npm run test
    node_js: 10
